name : cortex

uuid : 50a34350-0386-11e3-b92e-27b125b72560

description : "The Cortex project provides a set of high quality C++
libraries and Python modules tailored for software development in the
visual effects industry. Rather than producing end user tools, the
project focuses on creating a reusable set of modules of use to TDs and
programmers in a broad range of scenarios - allowing them to focus on
the more interesting or innovative aspects of development."

authors : [Image Engine]

config_version : 0

version : 8.0.0

variants :
- [ platform-linux, gcc-4.1.2, boost-1.47.0, python-2.6 ]
- [ platform-linux, gcc-4.1.2, boost-1.47.0, python-2.7 ]

requires :
- ilmbase-1.0.3
- openexr-1.7.1
- freeglut
- glew
- jpeg
- png
- tiff
- freetype2
- alembic-1.1.3
- hdf5

# build_requires:
# - doxygen

commands:
- export CMAKE_MODULE_PATH<<!ROOT!/cmake
- export PATH<<!ROOT!/bin
- export PYTHONPATH<<!ROOT!/lib/python2.7/site-packages
