name : ilmbase

uuid : 0a4ebec6-cfd7-11e2-9d77-001d4f455738

description : base ILM math libraries

homepage : http://www.openexr.com/

authors : [ILM]

config_version : 0

version : 2.0.1

variants :
- [ platform-linux, gcc-4.1.2 ]
- [ platform-linux, gcc-4.6 ]

external_build:
  url : http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.0.1.tar.gz
  sha1 : bfa62519094413f686c6f08c5923b47a10eea180
  # build out-of-source for pkgutils
  working_dir : build

  commands:
    - ${REZ_SOURCE_DIR}/configure --prefix=${REZ_INSTALL_PREFIX}
        --with-pic 
        --disable-debug
        --enable-shared=no
    - make -j8
    - make install

commands: |
  CMAKE_MODULE_PATH.prepend('{root}/cmake')
  # should probably avoid this unless we're building:
  LD_LIBRARY_PATH.prepend('{root}/lib')

